development:
  adapter: postgresql
  database: depot_development
  username: developer
  password: developer
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: depot_test
  username: developer
  password: developer
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: depot_production
  username: developer
  password: developer
  pool: 5
  timeout: 5000